### ISSUE TITLE
Error in downloading preprocessed data

### ISSUE THREAD

**Issue by Leirunlin** [qianghuangwhu/benchtemp#1]
''The datasets that have been preprocessed by BenchTemp are [Here](https://drive.google.com/drive/folders/1HKSFGEfxHDlHuQZ6nK4SLCEMFQIOtzpz?usp=sharing).''

I fail to download the preprocessed dataset via this link. Are there any updates in dataset downloading?

**Comment by johnnyhuangcs** [comment]
@Leirunlin Oh, the datasets is hosted on zenodo [here](https://zenodo.org/record/8267846) now.
You can download it via VPN.

The code to preprocess the relatively large graphs (DGraphFin, YouTubeReddit, and Taobao) is https://github.com/qianghuangwhu/benchtemp/tree/master/preprocess

**Comment by Leirunlin** [comment]
Thanks! The update helps a lot.
